//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string STRN_1 {
            get {
                return ResourceManager.GetString("STRN_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string STRN_10 {
            get {
                return ResourceManager.GetString("STRN_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Evacuation.
        /// </summary>
        internal static string STRN_11 {
            get {
                return ResourceManager.GetString("STRN_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Request.
        /// </summary>
        internal static string STRN_12 {
            get {
                return ResourceManager.GetString("STRN_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Statistics Report.
        /// </summary>
        internal static string STRN_13 {
            get {
                return ResourceManager.GetString("STRN_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Type.
        /// </summary>
        internal static string STRN_14 {
            get {
                return ResourceManager.GetString("STRN_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Details.
        /// </summary>
        internal static string STRN_15 {
            get {
                return ResourceManager.GetString("STRN_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visiting Details.
        /// </summary>
        internal static string STRN_16 {
            get {
                return ResourceManager.GetString("STRN_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string STRN_17 {
            get {
                return ResourceManager.GetString("STRN_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        internal static string STRN_18 {
            get {
                return ResourceManager.GetString("STRN_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string STRN_19 {
            get {
                return ResourceManager.GetString("STRN_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee/Host.
        /// </summary>
        internal static string STRN_2 {
            get {
                return ResourceManager.GetString("STRN_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        internal static string STRN_20 {
            get {
                return ResourceManager.GetString("STRN_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string STRN_21 {
            get {
                return ResourceManager.GetString("STRN_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Type.
        /// </summary>
        internal static string STRN_22 {
            get {
                return ResourceManager.GetString("STRN_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Server.
        /// </summary>
        internal static string STRN_23 {
            get {
                return ResourceManager.GetString("STRN_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string STRN_24 {
            get {
                return ResourceManager.GetString("STRN_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string STRN_25 {
            get {
                return ResourceManager.GetString("STRN_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSl Requied.
        /// </summary>
        internal static string STRN_26 {
            get {
                return ResourceManager.GetString("STRN_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Name.
        /// </summary>
        internal static string STRN_27 {
            get {
                return ResourceManager.GetString("STRN_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory Setting.
        /// </summary>
        internal static string STRN_28 {
            get {
                return ResourceManager.GetString("STRN_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service AccountName.
        /// </summary>
        internal static string STRN_29 {
            get {
                return ResourceManager.GetString("STRN_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Type.
        /// </summary>
        internal static string STRN_3 {
            get {
                return ResourceManager.GetString("STRN_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Path.
        /// </summary>
        internal static string STRN_30 {
            get {
                return ResourceManager.GetString("STRN_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Password.
        /// </summary>
        internal static string STRN_31 {
            get {
                return ResourceManager.GetString("STRN_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email For.
        /// </summary>
        internal static string STRN_32 {
            get {
                return ResourceManager.GetString("STRN_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Subject.
        /// </summary>
        internal static string STRN_33 {
            get {
                return ResourceManager.GetString("STRN_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Body.
        /// </summary>
        internal static string STRN_34 {
            get {
                return ResourceManager.GetString("STRN_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get AD.
        /// </summary>
        internal static string STRN_35 {
            get {
                return ResourceManager.GetString("STRN_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string STRN_36 {
            get {
                return ResourceManager.GetString("STRN_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string STRN_37 {
            get {
                return ResourceManager.GetString("STRN_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string STRN_38 {
            get {
                return ResourceManager.GetString("STRN_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        internal static string STRN_39 {
            get {
                return ResourceManager.GetString("STRN_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        internal static string STRN_4 {
            get {
                return ResourceManager.GetString("STRN_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string STRN_40 {
            get {
                return ResourceManager.GetString("STRN_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string STRN_41 {
            get {
                return ResourceManager.GetString("STRN_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Request.
        /// </summary>
        internal static string STRN_42 {
            get {
                return ResourceManager.GetString("STRN_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Request.
        /// </summary>
        internal static string STRN_43 {
            get {
                return ResourceManager.GetString("STRN_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Request.
        /// </summary>
        internal static string STRN_44 {
            get {
                return ResourceManager.GetString("STRN_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Request.
        /// </summary>
        internal static string STRN_45 {
            get {
                return ResourceManager.GetString("STRN_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string STRN_46 {
            get {
                return ResourceManager.GetString("STRN_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string STRN_47 {
            get {
                return ResourceManager.GetString("STRN_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Request Reports.
        /// </summary>
        internal static string STRN_48 {
            get {
                return ResourceManager.GetString("STRN_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        internal static string STRN_49 {
            get {
                return ResourceManager.GetString("STRN_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string STRN_5 {
            get {
                return ResourceManager.GetString("STRN_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee / Host.
        /// </summary>
        internal static string STRN_50 {
            get {
                return ResourceManager.GetString("STRN_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string STRN_51 {
            get {
                return ResourceManager.GetString("STRN_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string STRN_52 {
            get {
                return ResourceManager.GetString("STRN_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Name.
        /// </summary>
        internal static string STRN_53 {
            get {
                return ResourceManager.GetString("STRN_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Email.
        /// </summary>
        internal static string STRN_54 {
            get {
                return ResourceManager.GetString("STRN_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        internal static string STRN_6 {
            get {
                return ResourceManager.GetString("STRN_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval setting.
        /// </summary>
        internal static string STRN_7 {
            get {
                return ResourceManager.GetString("STRN_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail setting.
        /// </summary>
        internal static string STRN_8 {
            get {
                return ResourceManager.GetString("STRN_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Template.
        /// </summary>
        internal static string STRN_9 {
            get {
                return ResourceManager.GetString("STRN_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Detials.
        /// </summary>
        internal static string STR_1 {
            get {
                return ResourceManager.GetString("STR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visiting Detials.
        /// </summary>
        internal static string STR_10 {
            get {
                return ResourceManager.GetString("STR_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string STR_11 {
            get {
                return ResourceManager.GetString("STR_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string STR_12 {
            get {
                return ResourceManager.GetString("STR_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string STR_13 {
            get {
                return ResourceManager.GetString("STR_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Type.
        /// </summary>
        internal static string STR_14 {
            get {
                return ResourceManager.GetString("STR_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string STR_15 {
            get {
                return ResourceManager.GetString("STR_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string STR_16 {
            get {
                return ResourceManager.GetString("STR_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Data.
        /// </summary>
        internal static string STR_17 {
            get {
                return ResourceManager.GetString("STR_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check IN.
        /// </summary>
        internal static string STR_18 {
            get {
                return ResourceManager.GetString("STR_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string STR_19 {
            get {
                return ResourceManager.GetString("STR_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string STR_2 {
            get {
                return ResourceManager.GetString("STR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string STR_20 {
            get {
                return ResourceManager.GetString("STR_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        internal static string STR_21 {
            get {
                return ResourceManager.GetString("STR_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Out.
        /// </summary>
        internal static string STR_22 {
            get {
                return ResourceManager.GetString("STR_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch List.
        /// </summary>
        internal static string STR_23 {
            get {
                return ResourceManager.GetString("STR_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string STR_24 {
            get {
                return ResourceManager.GetString("STR_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Master Reports.
        /// </summary>
        internal static string STR_25 {
            get {
                return ResourceManager.GetString("STR_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Transaction.
        /// </summary>
        internal static string STR_26 {
            get {
                return ResourceManager.GetString("STR_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string STR_27 {
            get {
                return ResourceManager.GetString("STR_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string STR_28 {
            get {
                return ResourceManager.GetString("STR_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Leave.
        /// </summary>
        internal static string STR_29 {
            get {
                return ResourceManager.GetString("STR_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Number.
        /// </summary>
        internal static string STR_3 {
            get {
                return ResourceManager.GetString("STR_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Logout below if you are ready to end your current session..
        /// </summary>
        internal static string STR_30 {
            get {
                return ResourceManager.GetString("STR_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string STR_31 {
            get {
                return ResourceManager.GetString("STR_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string STR_32 {
            get {
                return ResourceManager.GetString("STR_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string STR_33 {
            get {
                return ResourceManager.GetString("STR_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string STR_34 {
            get {
                return ResourceManager.GetString("STR_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        internal static string STR_35 {
            get {
                return ResourceManager.GetString("STR_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Visitor Report.
        /// </summary>
        internal static string STR_36 {
            get {
                return ResourceManager.GetString("STR_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string STR_37 {
            get {
                return ResourceManager.GetString("STR_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Statistics Report.
        /// </summary>
        internal static string STR_38 {
            get {
                return ResourceManager.GetString("STR_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Name.
        /// </summary>
        internal static string STR_39 {
            get {
                return ResourceManager.GetString("STR_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        internal static string STR_4 {
            get {
                return ResourceManager.GetString("STR_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor ID.
        /// </summary>
        internal static string STR_40 {
            get {
                return ResourceManager.GetString("STR_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Watchlist.
        /// </summary>
        internal static string STR_41 {
            get {
                return ResourceManager.GetString("STR_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Export.
        /// </summary>
        internal static string STR_42 {
            get {
                return ResourceManager.GetString("STR_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Export.
        /// </summary>
        internal static string STR_43 {
            get {
                return ResourceManager.GetString("STR_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Image.
        /// </summary>
        internal static string STR_44 {
            get {
                return ResourceManager.GetString("STR_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string STR_45 {
            get {
                return ResourceManager.GetString("STR_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string STR_46 {
            get {
                return ResourceManager.GetString("STR_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Transaction Report.
        /// </summary>
        internal static string STR_47 {
            get {
                return ResourceManager.GetString("STR_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report.
        /// </summary>
        internal static string STR_48 {
            get {
                return ResourceManager.GetString("STR_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Registration.
        /// </summary>
        internal static string STR_49 {
            get {
                return ResourceManager.GetString("STR_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string STR_5 {
            get {
                return ResourceManager.GetString("STR_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Invite.
        /// </summary>
        internal static string STR_50 {
            get {
                return ResourceManager.GetString("STR_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester Information.
        /// </summary>
        internal static string STR_51 {
            get {
                return ResourceManager.GetString("STR_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Invite.
        /// </summary>
        internal static string STR_52 {
            get {
                return ResourceManager.GetString("STR_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester Name.
        /// </summary>
        internal static string STR_53 {
            get {
                return ResourceManager.GetString("STR_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Information.
        /// </summary>
        internal static string STR_54 {
            get {
                return ResourceManager.GetString("STR_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Name.
        /// </summary>
        internal static string STR_55 {
            get {
                return ResourceManager.GetString("STR_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string STR_56 {
            get {
                return ResourceManager.GetString("STR_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string STR_57 {
            get {
                return ResourceManager.GetString("STR_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string STR_58 {
            get {
                return ResourceManager.GetString("STR_58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string STR_59 {
            get {
                return ResourceManager.GetString("STR_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        internal static string STR_6 {
            get {
                return ResourceManager.GetString("STR_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string STR_60 {
            get {
                return ResourceManager.GetString("STR_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        internal static string STR_61 {
            get {
                return ResourceManager.GetString("STR_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Calender.
        /// </summary>
        internal static string STR_62 {
            get {
                return ResourceManager.GetString("STR_62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency.
        /// </summary>
        internal static string STR_63 {
            get {
                return ResourceManager.GetString("STR_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string STR_7 {
            get {
                return ResourceManager.GetString("STR_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string STR_8 {
            get {
                return ResourceManager.GetString("STR_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string STR_9 {
            get {
                return ResourceManager.GetString("STR_9", resourceCulture);
            }
        }
    }
}
